#!/usr/bin/env node
// openapi.json -> src/openapi.ts, schema.graphql -> src/graphql.ts.
// The inputs are written by the backend's generation mode (`pnpm gen:contracts`,
// task T031); until that exists there is nothing to generate and that is fine.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const openapiPath = join(root, 'openapi.json');
const graphqlPath = join(root, 'schema.graphql');

const hasOpenapi = existsSync(openapiPath);
const hasGraphql = existsSync(graphqlPath);

if (!hasOpenapi && !hasGraphql) {
  console.log(
    'contracts: nothing to generate — packages/contracts/openapi.json and schema.graphql\n' +
      '           do not exist yet. The backend writes them: run `pnpm gen:contracts`\n' +
      '           from the repository root once backend ships its generation mode.',
  );
  process.exit(0);
}

// Each input is generated from whatever surface exists. A missing one is not a
// half-finished run: the foundation ships REST commands before it ships a single
// GraphQL resolver, so `openapi.json` without `schema.graphql` is exactly what a
// correct P0 generation produces. Failing on it would make the phase unable to
// run its own script.
const banner = '// GENERATED by packages/contracts/scripts/generate.mjs — do not edit.\n';

if (hasOpenapi) {
  const { default: openapiTS, astToString } = await import('openapi-typescript');
  const ast = await openapiTS(pathToFileURL(openapiPath));
  writeFileSync(join(root, 'src', 'openapi.ts'), banner + astToString(ast));
  console.log('contracts: wrote src/openapi.ts');
} else {
  console.log('contracts: no openapi.json yet — skipping the REST types.');
}

if (hasGraphql) {
  const { buildSchema } = await import('graphql');
  const { plugin } = await import('@graphql-codegen/typescript');
  const schema = buildSchema(readFileSync(graphqlPath, 'utf8'));
  const out = await plugin(schema, [], {});
  const graphqlTs =
    typeof out === 'string'
      ? out
      : [...(out.prepend ?? []), out.content, ...(out.append ?? [])].join('\n');
  writeFileSync(join(root, 'src', 'graphql.ts'), banner + graphqlTs);
  console.log('contracts: wrote src/graphql.ts');
} else {
  console.log('contracts: no schema.graphql yet — the query surface arrives with its resolvers.');
}
