// GENERATED by packages/contracts/scripts/generate.mjs — do not edit.
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** A calendar date in the member's own time zone, as YYYY-MM-DD. */
  Date: { input: any; output: any; }
  /** An instant in time, serialised as an ISO 8601 string in UTC. */
  DateTime: { input: any; output: any; }
  /** Arbitrary JSON, used for a settings value and an audit entry’s metadata. */
  JSON: { input: any; output: any; }
};

export type BodyMetric = {
  __typename?: 'BodyMetric';
  bodyFatPct?: Maybe<Scalars['Float']['output']>;
  heightCm?: Maybe<Scalars['Float']['output']>;
  note?: Maybe<Scalars['String']['output']>;
  recordedAt: Scalars['DateTime']['output'];
  weightKg?: Maybe<Scalars['Float']['output']>;
};

export type Checkin = {
  __typename?: 'Checkin';
  adhered?: Maybe<Scalars['Boolean']['output']>;
  date: Scalars['Date']['output'];
  mood?: Maybe<Scalars['Int']['output']>;
  note?: Maybe<Scalars['String']['output']>;
};

export type Conversation = {
  __typename?: 'Conversation';
  archived: Scalars['Boolean']['output'];
  clearedUpToSeq: Scalars['Int']['output'];
  createdAt: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  kind: ConversationKind;
  lastMessageAt?: Maybe<Scalars['DateTime']['output']>;
  pinned: Scalars['Boolean']['output'];
  title: Scalars['String']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

/** The two chats an account comes with, and the ones a member starts. */
export enum ConversationKind {
  Coach = 'coach',
  Free = 'free',
  Planner = 'planner'
}

export type DailyPlan = {
  __typename?: 'DailyPlan';
  autoConfirmed: Scalars['Boolean']['output'];
  briefedAt?: Maybe<Scalars['DateTime']['output']>;
  confirmedAt?: Maybe<Scalars['DateTime']['output']>;
  date: Scalars['Date']['output'];
  mealLine?: Maybe<Scalars['String']['output']>;
  promptedAt?: Maybe<Scalars['DateTime']['output']>;
  status: PlanStatus;
  summarisedAt?: Maybe<Scalars['DateTime']['output']>;
  tasks: Array<PlanTask>;
  training?: Maybe<PlanTraining>;
  workoutLine?: Maybe<Scalars['String']['output']>;
};

export type Device = {
  __typename?: 'Device';
  hasPush: Scalars['Boolean']['output'];
  id: Scalars['ID']['output'];
  kind: DeviceKind;
  lastSeenAt?: Maybe<Scalars['DateTime']['output']>;
};

export enum DeviceKind {
  Android = 'android',
  ChromeExtension = 'chrome_extension',
  Ios = 'ios',
  Web = 'web'
}

export type Label = {
  __typename?: 'Label';
  color: Scalars['String']['output'];
  deletedAt?: Maybe<Scalars['DateTime']['output']>;
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  openTaskCount: Scalars['Int']['output'];
  sortOrder: Scalars['Int']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

export type LabelSnapshot = {
  __typename?: 'LabelSnapshot';
  color: Scalars['String']['output'];
  name: Scalars['String']['output'];
};

export type Message = {
  __typename?: 'Message';
  clientId?: Maybe<Scalars['String']['output']>;
  composedAt?: Maybe<Scalars['DateTime']['output']>;
  content: Scalars['String']['output'];
  conversationId: Scalars['ID']['output'];
  createdAt: Scalars['DateTime']['output'];
  intent?: Maybe<Scalars['JSON']['output']>;
  role: MessageRole;
  seq: Scalars['Int']['output'];
};

export type MessageConnection = {
  __typename?: 'MessageConnection';
  endCursor?: Maybe<Scalars['String']['output']>;
  hasNextPage: Scalars['Boolean']['output'];
  nodes: Array<Message>;
};

export enum MessageRole {
  Assistant = 'assistant',
  System = 'system',
  User = 'user'
}

/** What the member decided about a day: proposed and unanswered, agreed, or declined. A day with no plan at all reads as `draft` with no `promptedAt`. */
export enum PlanStatus {
  Confirmed = 'confirmed',
  Draft = 'draft',
  Skipped = 'skipped'
}

export type PlanTask = {
  __typename?: 'PlanTask';
  deferCount: Scalars['Int']['output'];
  dueAt?: Maybe<Scalars['DateTime']['output']>;
  id: Scalars['ID']['output'];
  priority: Scalars['Int']['output'];
  title: Scalars['String']['output'];
};

export type PlanTraining = {
  __typename?: 'PlanTraining';
  sessionId: Scalars['ID']['output'];
  sport: Scalars['String']['output'];
  startAt: Scalars['DateTime']['output'];
  title: Scalars['String']['output'];
};

export type Preferences = {
  __typename?: 'Preferences';
  aiSuggestions: Scalars['Boolean']['output'];
  checkinEnabled: Scalars['Boolean']['output'];
  endOfDayTime: Scalars['String']['output'];
  leadTimes: Array<Scalars['String']['output']>;
  mealMode: Scalars['String']['output'];
  meetingDurationMin: Scalars['Int']['output'];
  morningBriefingTime: Scalars['String']['output'];
  nextPracticeCutoff: Scalars['String']['output'];
  planTomorrowTime: Scalars['String']['output'];
  quietHours?: Maybe<QuietHours>;
  userId: Scalars['ID']['output'];
  weekStartsOn: Scalars['String']['output'];
};

export type Profile = {
  __typename?: 'Profile';
  allergies?: Maybe<Array<Scalars['String']['output']>>;
  bmi?: Maybe<Scalars['Float']['output']>;
  bodyMetrics: Array<BodyMetric>;
  displayName?: Maybe<Scalars['String']['output']>;
  foodDislikes?: Maybe<Array<Scalars['String']['output']>>;
  foodLikes?: Maybe<Array<Scalars['String']['output']>>;
  latestHeightCm?: Maybe<Scalars['Float']['output']>;
  latestWeightKg?: Maybe<Scalars['Float']['output']>;
  locale: Scalars['String']['output'];
  onboardingCompletedAt?: Maybe<Scalars['DateTime']['output']>;
  photoUrl?: Maybe<Scalars['String']['output']>;
  symptoms?: Maybe<Array<Scalars['String']['output']>>;
  timezone: Scalars['String']['output'];
  userId: Scalars['ID']['output'];
};

export type Query = {
  __typename?: 'Query';
  /** The caller's body metric history. */
  bodyMetrics: Array<BodyMetric>;
  checkins: Array<Checkin>;
  conversations: Array<Conversation>;
  /** A member's devices. Administrators only. */
  devicesOf: Array<Device>;
  labelPalette: Array<Scalars['String']['output']>;
  labels: Array<Label>;
  /** The authenticated member. */
  me: User;
  messages: MessageConnection;
  /** The caller's own registered devices. */
  myDevices: Array<Device>;
  plans: Array<DailyPlan>;
  /** The caller's own preferences. */
  preferences: Preferences;
  /** The caller's own profile. */
  profile: Profile;
  quickQuestions: Array<QuickQuestion>;
  reminder?: Maybe<Reminder>;
  reminders: ReminderPage;
  /** Registered machine callers. Administrators only. */
  serviceClients: Array<ServiceClient>;
  /** The settings registry. Administrators only. */
  settings: Array<Setting>;
  streak: Streak;
  task?: Maybe<Task>;
  tasks: TaskPage;
  todayPlan: DailyPlan;
  tomorrowDraft: DailyPlan;
  /** Every member. Administrators only. */
  users: UserConnection;
};


export type QueryBodyMetricsArgs = {
  last?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryCheckinsArgs = {
  from: Scalars['Date']['input'];
  to: Scalars['Date']['input'];
};


export type QueryConversationsArgs = {
  includeArchived?: InputMaybe<Scalars['Boolean']['input']>;
};


export type QueryDevicesOfArgs = {
  userId: Scalars['ID']['input'];
};


export type QueryLabelsArgs = {
  includeDeleted?: InputMaybe<Scalars['Boolean']['input']>;
};


export type QueryMessagesArgs = {
  afterSeq?: InputMaybe<Scalars['Int']['input']>;
  conversationId: Scalars['ID']['input'];
  first?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryPlansArgs = {
  from: Scalars['Date']['input'];
  to: Scalars['Date']['input'];
};


export type QueryQuickQuestionsArgs = {
  scope: ConversationKind;
};


export type QueryReminderArgs = {
  id: Scalars['ID']['input'];
};


export type QueryRemindersArgs = {
  cursor?: InputMaybe<Scalars['String']['input']>;
  limit?: InputMaybe<Scalars['Int']['input']>;
  view: ReminderViewName;
};


export type QueryTaskArgs = {
  id: Scalars['ID']['input'];
};


export type QueryTasksArgs = {
  cursor?: InputMaybe<Scalars['String']['input']>;
  labelId?: InputMaybe<Scalars['ID']['input']>;
  limit?: InputMaybe<Scalars['Int']['input']>;
  view: TaskViewName;
};


export type QueryTodayPlanArgs = {
  date?: InputMaybe<Scalars['Date']['input']>;
};


export type QueryUsersArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  role?: InputMaybe<Role>;
  search?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<UserStatus>;
};

export type QuickQuestion = {
  __typename?: 'QuickQuestion';
  id: Scalars['ID']['output'];
  isMine: Scalars['Boolean']['output'];
  mood: Scalars['String']['output'];
  scope: ConversationKind;
  text: Scalars['String']['output'];
};

export type QuietHours = {
  __typename?: 'QuietHours';
  from: Scalars['String']['output'];
  to: Scalars['String']['output'];
};

export type Reminder = {
  __typename?: 'Reminder';
  deletedAt?: Maybe<Scalars['DateTime']['output']>;
  effectiveAt: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  leadTimes: Array<Scalars['String']['output']>;
  remindAt: Scalars['DateTime']['output'];
  snoozedUntil?: Maybe<Scalars['DateTime']['output']>;
  source: Scalars['String']['output'];
  status: Scalars['String']['output'];
  title: Scalars['String']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

export type ReminderPage = {
  __typename?: 'ReminderPage';
  nextCursor?: Maybe<Scalars['String']['output']>;
  nodes: Array<Reminder>;
};

/** The four reminder lists. `done` carries cancelled ones too. */
export enum ReminderViewName {
  Deleted = 'deleted',
  Done = 'done',
  Overdue = 'overdue',
  Upcoming = 'upcoming'
}

export enum Role {
  Admin = 'admin',
  User = 'user'
}

export type ServiceClient = {
  __typename?: 'ServiceClient';
  createdAt: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  lastUsedAt?: Maybe<Scalars['DateTime']['output']>;
  name: Scalars['String']['output'];
  revokedAt?: Maybe<Scalars['DateTime']['output']>;
  scopes: Array<Scalars['String']['output']>;
};

export type Setting = {
  __typename?: 'Setting';
  defaultValue?: Maybe<Scalars['JSON']['output']>;
  description: Scalars['String']['output'];
  key: Scalars['String']['output'];
  readOnly: Scalars['Boolean']['output'];
  value?: Maybe<Scalars['JSON']['output']>;
};

export type Streak = {
  __typename?: 'Streak';
  best: Scalars['Int']['output'];
  current: Scalars['Int']['output'];
  lastAdheredDate?: Maybe<Scalars['Date']['output']>;
  weekAdherence: Array<Maybe<Scalars['Boolean']['output']>>;
};

export type Task = {
  __typename?: 'Task';
  allDay: Scalars['Boolean']['output'];
  completedAt?: Maybe<Scalars['DateTime']['output']>;
  deferCount: Scalars['Int']['output'];
  deletedAt?: Maybe<Scalars['DateTime']['output']>;
  dueAt?: Maybe<Scalars['DateTime']['output']>;
  estimatedMinutes?: Maybe<Scalars['Int']['output']>;
  id: Scalars['ID']['output'];
  label?: Maybe<LabelSnapshot>;
  labelId?: Maybe<Scalars['ID']['output']>;
  notes?: Maybe<Scalars['String']['output']>;
  priority: Scalars['Int']['output'];
  recurrenceMode?: Maybe<Scalars['String']['output']>;
  recurrenceText?: Maybe<Scalars['String']['output']>;
  repeats: Scalars['Boolean']['output'];
  source: Scalars['String']['output'];
  status: Scalars['String']['output'];
  title: Scalars['String']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

export type TaskPage = {
  __typename?: 'TaskPage';
  nextCursor?: Maybe<Scalars['String']['output']>;
  nodes: Array<Task>;
};

/** The six task lists, named as the member sees them. */
export enum TaskViewName {
  Completed = 'completed',
  Deleted = 'deleted',
  Label = 'label',
  Overdue = 'overdue',
  Today = 'today',
  Upcoming = 'upcoming'
}

export type User = {
  __typename?: 'User';
  createdAt: Scalars['DateTime']['output'];
  deviceCount: Scalars['Int']['output'];
  displayName?: Maybe<Scalars['String']['output']>;
  email: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  lastLoginAt?: Maybe<Scalars['DateTime']['output']>;
  role: Role;
  status: UserStatus;
};

export type UserConnection = {
  __typename?: 'UserConnection';
  endCursor?: Maybe<Scalars['String']['output']>;
  hasNextPage: Scalars['Boolean']['output'];
  nodes: Array<User>;
};

export enum UserStatus {
  Active = 'active',
  Banned = 'banned'
}
