// GENERATED by packages/contracts/scripts/generate.mjs — do not edit.
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** A calendar date in the member's own time zone, as YYYY-MM-DD. */
  Date: { input: any; output: any; }
  /** An instant in time, serialised as an ISO 8601 string in UTC. */
  DateTime: { input: any; output: any; }
  /** Arbitrary JSON, used for a settings value and an audit entry’s metadata. */
  JSON: { input: any; output: any; }
};

export type AgendaDay = {
  __typename?: 'AgendaDay';
  date: Scalars['Date']['output'];
  items: Array<AgendaItem>;
};

export type AgendaItem = {
  __typename?: 'AgendaItem';
  allDay: Scalars['Boolean']['output'];
  color?: Maybe<Scalars['String']['output']>;
  endAt?: Maybe<Scalars['DateTime']['output']>;
  event?: Maybe<CalendarEvent>;
  id: Scalars['ID']['output'];
  kind: AgendaKind;
  meeting?: Maybe<Meeting>;
  occurrenceAt: Scalars['DateTime']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
};

/** What a row on the agenda is. `prep` is its own kind rather than an attribute of a meeting, because half an hour of preparation is half an hour that is not free (FR-002). */
export enum AgendaKind {
  Event = 'event',
  Meeting = 'meeting',
  Prep = 'prep',
  Session = 'session',
  Task = 'task'
}

export type AgendaKindCounts = {
  __typename?: 'AgendaKindCounts';
  event: Scalars['Int']['output'];
  meeting: Scalars['Int']['output'];
  prep: Scalars['Int']['output'];
  session: Scalars['Int']['output'];
  task: Scalars['Int']['output'];
};

export type AthleteProfile = {
  __typename?: 'AthleteProfile';
  slots: Array<Slot>;
  sports: Array<Scalars['String']['output']>;
};

export type AuditConnection = {
  __typename?: 'AuditConnection';
  endCursor?: Maybe<Scalars['String']['output']>;
  hasNextPage: Scalars['Boolean']['output'];
  nodes: Array<AuditEntry>;
};

export type AuditEntry = {
  __typename?: 'AuditEntry';
  action: Scalars['String']['output'];
  actorId: Scalars['ID']['output'];
  actorLabel: Scalars['String']['output'];
  actorType: Scalars['String']['output'];
  at: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  meta?: Maybe<Scalars['JSON']['output']>;
  targetId?: Maybe<Scalars['ID']['output']>;
  targetType: Scalars['String']['output'];
};

export type BodyMetric = {
  __typename?: 'BodyMetric';
  bodyFatPct?: Maybe<Scalars['Float']['output']>;
  heightCm?: Maybe<Scalars['Float']['output']>;
  note?: Maybe<Scalars['String']['output']>;
  recordedAt: Scalars['DateTime']['output'];
  weightKg?: Maybe<Scalars['Float']['output']>;
};

export type CalendarEvent = {
  __typename?: 'CalendarEvent';
  allDay: Scalars['Boolean']['output'];
  color?: Maybe<Scalars['String']['output']>;
  endAt: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  notes?: Maybe<Scalars['String']['output']>;
  recurrence?: Maybe<MeetingRecurrence>;
  startAt: Scalars['DateTime']['output'];
  title: Scalars['String']['output'];
};

export type Checkin = {
  __typename?: 'Checkin';
  adhered?: Maybe<Scalars['Boolean']['output']>;
  date: Scalars['Date']['output'];
  mood?: Maybe<Scalars['Int']['output']>;
  note?: Maybe<Scalars['String']['output']>;
};

export type ChosenMeal = {
  __typename?: 'ChosenMeal';
  kind: MealKind;
  mealId?: Maybe<Scalars['ID']['output']>;
  name: Scalars['String']['output'];
};

export type Conversation = {
  __typename?: 'Conversation';
  archived: Scalars['Boolean']['output'];
  clearedUpToSeq: Scalars['Int']['output'];
  createdAt: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  kind: ConversationKind;
  lastMessageAt?: Maybe<Scalars['DateTime']['output']>;
  pinned: Scalars['Boolean']['output'];
  title: Scalars['String']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

/** The two chats an account comes with, and the ones a member starts. */
export enum ConversationKind {
  Coach = 'coach',
  Free = 'free',
  Planner = 'planner'
}

export type DailyPlan = {
  __typename?: 'DailyPlan';
  autoConfirmed: Scalars['Boolean']['output'];
  briefedAt?: Maybe<Scalars['DateTime']['output']>;
  confirmedAt?: Maybe<Scalars['DateTime']['output']>;
  date: Scalars['Date']['output'];
  dayLine: Scalars['String']['output'];
  mealLine?: Maybe<Scalars['String']['output']>;
  mealReason?: Maybe<Scalars['String']['output']>;
  promptedAt?: Maybe<Scalars['DateTime']['output']>;
  status: PlanStatus;
  summarisedAt?: Maybe<Scalars['DateTime']['output']>;
  tasks: Array<PlanTask>;
  training?: Maybe<PlanTraining>;
  workoutLine?: Maybe<Scalars['String']['output']>;
};

export type Device = {
  __typename?: 'Device';
  hasPush: Scalars['Boolean']['output'];
  id: Scalars['ID']['output'];
  kind: DeviceKind;
  lastSeenAt?: Maybe<Scalars['DateTime']['output']>;
};

export enum DeviceKind {
  Android = 'android',
  ChromeExtension = 'chrome_extension',
  Ios = 'ios',
  Web = 'web'
}

export type Exercise = {
  __typename?: 'Exercise';
  id: Scalars['ID']['output'];
  mediaRefs: Array<MediaRef>;
  name: Scalars['String']['output'];
  notes?: Maybe<Scalars['String']['output']>;
  sets: Array<SetEntry>;
};

export type KnowledgeDoc = {
  __typename?: 'KnowledgeDoc';
  author?: Maybe<Scalars['String']['output']>;
  durationSec?: Maybe<Scalars['Int']['output']>;
  hadTranscript?: Maybe<Scalars['Boolean']['output']>;
  keyPoints: Array<Scalars['String']['output']>;
  lengthChars: Scalars['Int']['output'];
  media: Array<SourceMedia>;
  publishedAt?: Maybe<Scalars['DateTime']['output']>;
  readAt: Scalars['DateTime']['output'];
  summary: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
};

export type Label = {
  __typename?: 'Label';
  color: Scalars['String']['output'];
  deletedAt?: Maybe<Scalars['DateTime']['output']>;
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  openTaskCount: Scalars['Int']['output'];
  sortOrder: Scalars['Int']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

export type LabelSnapshot = {
  __typename?: 'LabelSnapshot';
  color: Scalars['String']['output'];
  name: Scalars['String']['output'];
};

export type Link = {
  __typename?: 'Link';
  addedAt: Scalars['DateTime']['output'];
  attempts: Scalars['Int']['output'];
  children: Array<Link>;
  doc?: Maybe<KnowledgeDoc>;
  failReason?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  kind: LinkKind;
  parentId?: Maybe<Scalars['ID']['output']>;
  processedAt?: Maybe<Scalars['DateTime']['output']>;
  skippedCount?: Maybe<Scalars['Int']['output']>;
  status: LinkStatus;
  tags: Array<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  url: Scalars['String']['output'];
};

export type LinkConnection = {
  __typename?: 'LinkConnection';
  endCursor?: Maybe<Scalars['String']['output']>;
  hasNextPage: Scalars['Boolean']['output'];
  nodes: Array<Link>;
};

export enum LinkKind {
  Article = 'article',
  Playlist = 'playlist',
  Video = 'video',
  Website = 'website'
}

export enum LinkStatus {
  Done = 'done',
  Extracting = 'extracting',
  Failed = 'failed',
  Fetching = 'fetching',
  Queued = 'queued',
  Summarising = 'summarising'
}

export type Location = {
  __typename?: 'Location';
  address?: Maybe<Scalars['String']['output']>;
  onlineLink?: Maybe<Scalars['String']['output']>;
};

export type Meal = {
  __typename?: 'Meal';
  id: Scalars['ID']['output'];
  ingredients: Array<Scalars['String']['output']>;
  kind: MealKind;
  name: Scalars['String']['output'];
  tags: Array<Scalars['String']['output']>;
  updatedAt: Scalars['DateTime']['output'];
};

export enum MealKind {
  Any = 'any',
  Breakfast = 'breakfast',
  Dinner = 'dinner',
  Lunch = 'lunch',
  Snack = 'snack'
}

export enum MealMode {
  Library = 'library',
  Llm = 'llm'
}

export type MediaRef = {
  __typename?: 'MediaRef';
  caption?: Maybe<Scalars['String']['output']>;
  type: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type Meeting = {
  __typename?: 'Meeting';
  allDay: Scalars['Boolean']['output'];
  description?: Maybe<Scalars['String']['output']>;
  durationMin: Scalars['Int']['output'];
  id: Scalars['ID']['output'];
  location: Location;
  lockTimezone?: Maybe<Scalars['String']['output']>;
  nextOccurrence?: Maybe<Scalars['DateTime']['output']>;
  prepMinutes: Scalars['Int']['output'];
  prepNotes?: Maybe<Scalars['String']['output']>;
  recurrence?: Maybe<MeetingRecurrence>;
  reminderOffsets: Array<Scalars['Int']['output']>;
  startAt: Scalars['DateTime']['output'];
  status: MeetingStatus;
  title: Scalars['String']['output'];
};

export type MeetingOccurrence = {
  __typename?: 'MeetingOccurrence';
  durationMin: Scalars['Int']['output'];
  endAt: Scalars['DateTime']['output'];
  location: Location;
  meetingId: Scalars['ID']['output'];
  moved: Scalars['Boolean']['output'];
  originalStart: Scalars['DateTime']['output'];
  prepMinutes: Scalars['Int']['output'];
  reminderOffsets: Array<Scalars['Int']['output']>;
  startAt: Scalars['DateTime']['output'];
  title: Scalars['String']['output'];
};

export type MeetingRecurrence = {
  __typename?: 'MeetingRecurrence';
  dtstart: Scalars['DateTime']['output'];
  exdates: Array<Scalars['DateTime']['output']>;
  humanText: Scalars['String']['output'];
  overrides: Array<Override>;
  rrule: Scalars['String']['output'];
};

/** In the diary, it happened, or it is off. Deleting never changes it — the status is the only record of which, and the Deleted view exists to show exactly that. */
export enum MeetingStatus {
  Cancelled = 'cancelled',
  Completed = 'completed',
  Scheduled = 'scheduled'
}

export type Message = {
  __typename?: 'Message';
  clientId?: Maybe<Scalars['String']['output']>;
  composedAt?: Maybe<Scalars['DateTime']['output']>;
  content: Scalars['String']['output'];
  conversationId: Scalars['ID']['output'];
  createdAt: Scalars['DateTime']['output'];
  intent?: Maybe<Scalars['JSON']['output']>;
  role: MessageRole;
  seq: Scalars['Int']['output'];
};

export type MessageConnection = {
  __typename?: 'MessageConnection';
  endCursor?: Maybe<Scalars['String']['output']>;
  hasNextPage: Scalars['Boolean']['output'];
  nodes: Array<Message>;
};

export enum MessageRole {
  Assistant = 'assistant',
  System = 'system',
  User = 'user'
}

export type MonthDay = {
  __typename?: 'MonthDay';
  busy: Scalars['Boolean']['output'];
  byKind: AgendaKindCounts;
  date: Scalars['Date']['output'];
  total: Scalars['Int']['output'];
};

export type NextPractice = {
  __typename?: 'NextPractice';
  isToday: Scalars['Boolean']['output'];
  /** 'today' | 'after-cutoff' | 'none-scheduled' */
  reason: Scalars['String']['output'];
  session?: Maybe<Session>;
};

export type Override = {
  __typename?: 'Override';
  durationMin?: Maybe<Scalars['Int']['output']>;
  location?: Maybe<Location>;
  originalStart: Scalars['DateTime']['output'];
  startAt?: Maybe<Scalars['DateTime']['output']>;
  title?: Maybe<Scalars['String']['output']>;
};

/** What the member decided about a day: proposed and unanswered, agreed, or declined. A day with no plan at all reads as `draft` with no `promptedAt`. */
export enum PlanStatus {
  Confirmed = 'confirmed',
  Draft = 'draft',
  Skipped = 'skipped'
}

export type PlanTask = {
  __typename?: 'PlanTask';
  deferCount: Scalars['Int']['output'];
  dueAt?: Maybe<Scalars['DateTime']['output']>;
  id: Scalars['ID']['output'];
  priority: Scalars['Int']['output'];
  title: Scalars['String']['output'];
};

export type PlanTraining = {
  __typename?: 'PlanTraining';
  sessionId: Scalars['ID']['output'];
  sport: Scalars['String']['output'];
  startAt: Scalars['DateTime']['output'];
  title: Scalars['String']['output'];
};

export type Preferences = {
  __typename?: 'Preferences';
  aiSuggestions: Scalars['Boolean']['output'];
  checkinEnabled: Scalars['Boolean']['output'];
  endOfDayTime: Scalars['String']['output'];
  leadTimes: Array<Scalars['String']['output']>;
  mealMode: Scalars['String']['output'];
  meetingDurationMin: Scalars['Int']['output'];
  morningBriefingTime: Scalars['String']['output'];
  nextPracticeCutoff: Scalars['String']['output'];
  planTomorrowTime: Scalars['String']['output'];
  quietHours?: Maybe<QuietHours>;
  userId: Scalars['ID']['output'];
  weekStartsOn: Scalars['String']['output'];
};

export type Profile = {
  __typename?: 'Profile';
  allergies?: Maybe<Array<Scalars['String']['output']>>;
  bmi?: Maybe<Scalars['Float']['output']>;
  bodyMetrics: Array<BodyMetric>;
  displayName?: Maybe<Scalars['String']['output']>;
  foodDislikes?: Maybe<Array<Scalars['String']['output']>>;
  foodLikes?: Maybe<Array<Scalars['String']['output']>>;
  latestHeightCm?: Maybe<Scalars['Float']['output']>;
  latestWeightKg?: Maybe<Scalars['Float']['output']>;
  locale: Scalars['String']['output'];
  onboardingCompletedAt?: Maybe<Scalars['DateTime']['output']>;
  photoUrl?: Maybe<Scalars['String']['output']>;
  symptoms?: Maybe<Array<Scalars['String']['output']>>;
  timezone: Scalars['String']['output'];
  userId: Scalars['ID']['output'];
};

export type Program = {
  __typename?: 'Program';
  appliedStartDate?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  source: Scalars['String']['output'];
  sourceLinkIds: Array<Scalars['ID']['output']>;
  sport: Scalars['String']['output'];
  status: Scalars['String']['output'];
  title: Scalars['String']['output'];
  weeks: Array<ProgramWeek>;
};

export type ProgramSessionTemplate = {
  __typename?: 'ProgramSessionTemplate';
  exercises: Array<TemplateExercise>;
  focus?: Maybe<Scalars['String']['output']>;
  templateId: Scalars['ID']['output'];
  title: Scalars['String']['output'];
  weekday?: Maybe<Scalars['Int']['output']>;
};

export type ProgramWeek = {
  __typename?: 'ProgramWeek';
  index: Scalars['Int']['output'];
  sessions: Array<ProgramSessionTemplate>;
};

export type Query = {
  __typename?: 'Query';
  agenda: Array<AgendaDay>;
  athleteProfile: AthleteProfile;
  /** Who did what, and when. Administrators only. */
  audit: AuditConnection;
  /** The caller's body metric history. */
  bodyMetrics: Array<BodyMetric>;
  checkins: Array<Checkin>;
  conversations: Array<Conversation>;
  /** A member's devices. Administrators only. */
  devicesOf: Array<Device>;
  /** Every member’s unfinished links. Administrators only. */
  ingestionQueue: Array<Link>;
  labelPalette: Array<Scalars['String']['output']>;
  labels: Array<Label>;
  /** One saved link with its summary and, for a playlist, its videos. */
  link?: Maybe<Link>;
  /** The member’s saved links, newest first. */
  links: LinkConnection;
  /** The authenticated member. */
  me: User;
  /** The member’s own meals, by name. */
  meals: Array<Meal>;
  meeting?: Maybe<Meeting>;
  meetingOccurrences: Array<MeetingOccurrence>;
  meetings: Array<Meeting>;
  messages: MessageConnection;
  monthOverview: Array<MonthDay>;
  /** The caller's own registered devices. */
  myDevices: Array<Device>;
  nextPractice: NextPractice;
  plans: Array<DailyPlan>;
  /** The caller's own preferences. */
  preferences: Preferences;
  /** The caller's own profile. */
  profile: Profile;
  program?: Maybe<Program>;
  programs: Array<Program>;
  quickQuestions: Array<QuickQuestion>;
  reminder?: Maybe<Reminder>;
  reminders: ReminderPage;
  /** Registered machine callers. Administrators only. */
  serviceClients: Array<ServiceClient>;
  session?: Maybe<Session>;
  sessions: Array<Session>;
  /** The settings registry. Administrators only. */
  settings: Array<Setting>;
  streak: Streak;
  /** Session suggestions drawn from the member’s own saved sources. */
  suggestions: Array<Suggestion>;
  task?: Maybe<Task>;
  tasks: TaskPage;
  /** The meals chosen for one of the member’s days, or null when none have been. */
  todayMeals?: Maybe<TodayMeals>;
  todayPlan: DailyPlan;
  tomorrowDraft: DailyPlan;
  /** Model use by day, kind and model — and by member when asked. Administrators only. */
  usage: Array<UsageRow>;
  /** Every member. Administrators only. */
  users: UserConnection;
  workouts: Array<Workout>;
};


export type QueryAgendaArgs = {
  from: Scalars['DateTime']['input'];
  to: Scalars['DateTime']['input'];
};


export type QueryAuditArgs = {
  action?: InputMaybe<Scalars['String']['input']>;
  actor?: InputMaybe<Scalars['ID']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  from?: InputMaybe<Scalars['DateTime']['input']>;
  targetType?: InputMaybe<Scalars['String']['input']>;
  to?: InputMaybe<Scalars['DateTime']['input']>;
};


export type QueryBodyMetricsArgs = {
  last?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryCheckinsArgs = {
  from: Scalars['Date']['input'];
  to: Scalars['Date']['input'];
};


export type QueryConversationsArgs = {
  includeArchived?: InputMaybe<Scalars['Boolean']['input']>;
};


export type QueryDevicesOfArgs = {
  userId: Scalars['ID']['input'];
};


export type QueryIngestionQueueArgs = {
  status?: InputMaybe<LinkStatus>;
};


export type QueryLabelsArgs = {
  includeDeleted?: InputMaybe<Scalars['Boolean']['input']>;
};


export type QueryLinkArgs = {
  id: Scalars['ID']['input'];
};


export type QueryLinksArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  kind?: InputMaybe<LinkKind>;
  status?: InputMaybe<LinkStatus>;
};


export type QueryMealsArgs = {
  kind?: InputMaybe<MealKind>;
};


export type QueryMeetingArgs = {
  id: Scalars['ID']['input'];
};


export type QueryMeetingOccurrencesArgs = {
  from: Scalars['DateTime']['input'];
  to: Scalars['DateTime']['input'];
};


export type QueryMeetingsArgs = {
  includeCompleted?: InputMaybe<Scalars['Boolean']['input']>;
};


export type QueryMessagesArgs = {
  afterSeq?: InputMaybe<Scalars['Int']['input']>;
  conversationId: Scalars['ID']['input'];
  first?: InputMaybe<Scalars['Int']['input']>;
};


export type QueryMonthOverviewArgs = {
  month: Scalars['Int']['input'];
  year: Scalars['Int']['input'];
};


export type QueryPlansArgs = {
  from: Scalars['Date']['input'];
  to: Scalars['Date']['input'];
};


export type QueryProgramArgs = {
  id: Scalars['ID']['input'];
};


export type QueryProgramsArgs = {
  includeArchived?: InputMaybe<Scalars['Boolean']['input']>;
};


export type QueryQuickQuestionsArgs = {
  scope: ConversationKind;
};


export type QueryReminderArgs = {
  id: Scalars['ID']['input'];
};


export type QueryRemindersArgs = {
  cursor?: InputMaybe<Scalars['String']['input']>;
  limit?: InputMaybe<Scalars['Int']['input']>;
  view: ReminderViewName;
};


export type QuerySessionArgs = {
  id: Scalars['ID']['input'];
};


export type QuerySessionsArgs = {
  from: Scalars['DateTime']['input'];
  to: Scalars['DateTime']['input'];
};


export type QuerySuggestionsArgs = {
  status?: InputMaybe<SuggestionStatus>;
};


export type QueryTaskArgs = {
  id: Scalars['ID']['input'];
};


export type QueryTasksArgs = {
  cursor?: InputMaybe<Scalars['String']['input']>;
  labelId?: InputMaybe<Scalars['ID']['input']>;
  limit?: InputMaybe<Scalars['Int']['input']>;
  view: TaskViewName;
};


export type QueryTodayMealsArgs = {
  date?: InputMaybe<Scalars['Date']['input']>;
};


export type QueryTodayPlanArgs = {
  date?: InputMaybe<Scalars['Date']['input']>;
};


export type QueryUsageArgs = {
  byMember?: InputMaybe<Scalars['Boolean']['input']>;
  from: Scalars['Date']['input'];
  to: Scalars['Date']['input'];
  userId?: InputMaybe<Scalars['ID']['input']>;
};


export type QueryUsersArgs = {
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  role?: InputMaybe<Role>;
  search?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<UserStatus>;
};


export type QueryWorkoutsArgs = {
  sport?: InputMaybe<Scalars['String']['input']>;
};

export type QuickQuestion = {
  __typename?: 'QuickQuestion';
  id: Scalars['ID']['output'];
  isMine: Scalars['Boolean']['output'];
  mood: Scalars['String']['output'];
  scope: ConversationKind;
  text: Scalars['String']['output'];
};

export type QuietHours = {
  __typename?: 'QuietHours';
  from: Scalars['String']['output'];
  to: Scalars['String']['output'];
};

export type Reminder = {
  __typename?: 'Reminder';
  deletedAt?: Maybe<Scalars['DateTime']['output']>;
  effectiveAt: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  leadTimes: Array<Scalars['String']['output']>;
  remindAt: Scalars['DateTime']['output'];
  snoozedUntil?: Maybe<Scalars['DateTime']['output']>;
  source: Scalars['String']['output'];
  status: Scalars['String']['output'];
  title: Scalars['String']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

export type ReminderPage = {
  __typename?: 'ReminderPage';
  nextCursor?: Maybe<Scalars['String']['output']>;
  nodes: Array<Reminder>;
};

/** The four reminder lists. `done` carries cancelled ones too. */
export enum ReminderViewName {
  Deleted = 'deleted',
  Done = 'done',
  Overdue = 'overdue',
  Upcoming = 'upcoming'
}

export enum Role {
  Admin = 'admin',
  User = 'user'
}

export type ServiceClient = {
  __typename?: 'ServiceClient';
  createdAt: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  lastUsedAt?: Maybe<Scalars['DateTime']['output']>;
  name: Scalars['String']['output'];
  revokedAt?: Maybe<Scalars['DateTime']['output']>;
  scopes: Array<Scalars['String']['output']>;
};

export type Session = {
  __typename?: 'Session';
  completedAt?: Maybe<Scalars['DateTime']['output']>;
  durationMin: Scalars['Int']['output'];
  exercises: Array<Exercise>;
  focus?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  isMissed: Scalars['Boolean']['output'];
  notes?: Maybe<Scalars['String']['output']>;
  plannedAt: Scalars['DateTime']['output'];
  programId?: Maybe<Scalars['ID']['output']>;
  sport: Scalars['String']['output'];
  status: SessionStatus;
  suggestionId?: Maybe<Scalars['ID']['output']>;
  title: Scalars['String']['output'];
  weekIndex?: Maybe<Scalars['Int']['output']>;
};

/** Planned, done, called off, or deliberately not done. A skipped session stays in the week so the record is honest, and deleting one never changes its status. */
export enum SessionStatus {
  Cancelled = 'cancelled',
  Completed = 'completed',
  Planned = 'planned',
  Skipped = 'skipped'
}

export type SetEntry = {
  __typename?: 'SetEntry';
  actualDistanceM?: Maybe<Scalars['Int']['output']>;
  actualDurationSec?: Maybe<Scalars['Int']['output']>;
  actualReps?: Maybe<Scalars['Int']['output']>;
  actualWeightKg?: Maybe<Scalars['Float']['output']>;
  done: Scalars['Boolean']['output'];
  targetDistanceM?: Maybe<Scalars['Int']['output']>;
  targetDurationSec?: Maybe<Scalars['Int']['output']>;
  targetReps?: Maybe<Scalars['Int']['output']>;
  targetWeightKg?: Maybe<Scalars['Float']['output']>;
};

export type Setting = {
  __typename?: 'Setting';
  control: Scalars['JSON']['output'];
  defaultValue?: Maybe<Scalars['JSON']['output']>;
  description: Scalars['String']['output'];
  key: Scalars['String']['output'];
  readOnly: Scalars['Boolean']['output'];
  value?: Maybe<Scalars['JSON']['output']>;
};

export type Slot = {
  __typename?: 'Slot';
  durationMin: Scalars['Int']['output'];
  id: Scalars['ID']['output'];
  location?: Maybe<Scalars['String']['output']>;
  sport: Scalars['String']['output'];
  start: Scalars['String']['output'];
  weekday: Scalars['Int']['output'];
};

export type SourceMedia = {
  __typename?: 'SourceMedia';
  caption?: Maybe<Scalars['String']['output']>;
  type: Scalars['String']['output'];
  url?: Maybe<Scalars['String']['output']>;
};

export type Streak = {
  __typename?: 'Streak';
  best: Scalars['Int']['output'];
  current: Scalars['Int']['output'];
  lastAdheredDate?: Maybe<Scalars['Date']['output']>;
  weekAdherence: Array<Maybe<Scalars['Boolean']['output']>>;
};

export type SuggestedExercise = {
  __typename?: 'SuggestedExercise';
  name: Scalars['String']['output'];
  notes?: Maybe<Scalars['String']['output']>;
  sets: Array<SuggestedSet>;
};

export type SuggestedSet = {
  __typename?: 'SuggestedSet';
  targetDistanceM?: Maybe<Scalars['Int']['output']>;
  targetDurationSec?: Maybe<Scalars['Int']['output']>;
  targetReps?: Maybe<Scalars['Int']['output']>;
  targetWeightKg?: Maybe<Scalars['Float']['output']>;
};

export type Suggestion = {
  __typename?: 'Suggestion';
  acceptedSessionId?: Maybe<Scalars['ID']['output']>;
  createdAt: Scalars['DateTime']['output'];
  draft: SuggestionDraft;
  forDate: Scalars['Date']['output'];
  id: Scalars['ID']['output'];
  outcome?: Maybe<Scalars['String']['output']>;
  rationale: Scalars['String']['output'];
  sessionId?: Maybe<Scalars['ID']['output']>;
  sources: Array<SuggestionSource>;
  sport: Scalars['String']['output'];
  status: SuggestionStatus;
};

export type SuggestionDraft = {
  __typename?: 'SuggestionDraft';
  exercises: Array<SuggestedExercise>;
  focus?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
};

export type SuggestionSource = {
  __typename?: 'SuggestionSource';
  id: Scalars['ID']['output'];
  title?: Maybe<Scalars['String']['output']>;
  url: Scalars['String']['output'];
};

export enum SuggestionStatus {
  Accepted = 'accepted',
  Dismissed = 'dismissed',
  Pending = 'pending'
}

export type Task = {
  __typename?: 'Task';
  allDay: Scalars['Boolean']['output'];
  completedAt?: Maybe<Scalars['DateTime']['output']>;
  deferCount: Scalars['Int']['output'];
  deletedAt?: Maybe<Scalars['DateTime']['output']>;
  dueAt?: Maybe<Scalars['DateTime']['output']>;
  estimatedMinutes?: Maybe<Scalars['Int']['output']>;
  id: Scalars['ID']['output'];
  label?: Maybe<LabelSnapshot>;
  labelId?: Maybe<Scalars['ID']['output']>;
  notes?: Maybe<Scalars['String']['output']>;
  priority: Scalars['Int']['output'];
  recurrenceMode?: Maybe<Scalars['String']['output']>;
  recurrenceText?: Maybe<Scalars['String']['output']>;
  repeats: Scalars['Boolean']['output'];
  source: Scalars['String']['output'];
  status: Scalars['String']['output'];
  title: Scalars['String']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

export type TaskPage = {
  __typename?: 'TaskPage';
  nextCursor?: Maybe<Scalars['String']['output']>;
  nodes: Array<Task>;
};

/** The six task lists, named as the member sees them. */
export enum TaskViewName {
  Completed = 'completed',
  Deleted = 'deleted',
  Label = 'label',
  Overdue = 'overdue',
  Today = 'today',
  Upcoming = 'upcoming'
}

export type TemplateExercise = {
  __typename?: 'TemplateExercise';
  mediaRefs: Array<MediaRef>;
  name: Scalars['String']['output'];
  notes?: Maybe<Scalars['String']['output']>;
  sets: Array<TemplateSet>;
};

export type TemplateSet = {
  __typename?: 'TemplateSet';
  targetDistanceM?: Maybe<Scalars['Int']['output']>;
  targetDurationSec?: Maybe<Scalars['Int']['output']>;
  targetReps?: Maybe<Scalars['Int']['output']>;
  targetWeightKg?: Maybe<Scalars['Float']['output']>;
};

export type TodayMeals = {
  __typename?: 'TodayMeals';
  date: Scalars['Date']['output'];
  line?: Maybe<Scalars['String']['output']>;
  meals: Array<ChosenMeal>;
  mode: MealMode;
  withheldReason?: Maybe<WithheldReason>;
};

export type UsageRow = {
  __typename?: 'UsageRow';
  calls: Scalars['Int']['output'];
  completionTokens: Scalars['Int']['output'];
  day: Scalars['Date']['output'];
  kind: Scalars['String']['output'];
  model: Scalars['String']['output'];
  promptTokens: Scalars['Int']['output'];
  userId?: Maybe<Scalars['ID']['output']>;
};

export type User = {
  __typename?: 'User';
  createdAt: Scalars['DateTime']['output'];
  deviceCount: Scalars['Int']['output'];
  displayName?: Maybe<Scalars['String']['output']>;
  email: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  lastLoginAt?: Maybe<Scalars['DateTime']['output']>;
  role: Role;
  status: UserStatus;
};

export type UserConnection = {
  __typename?: 'UserConnection';
  endCursor?: Maybe<Scalars['String']['output']>;
  hasNextPage: Scalars['Boolean']['output'];
  nodes: Array<User>;
};

export enum UserStatus {
  Active = 'active',
  Banned = 'banned'
}

export enum WithheldReason {
  Allergen = 'allergen',
  EmptyLibrary = 'empty_library',
  ModelUnavailable = 'model_unavailable'
}

export type Workout = {
  __typename?: 'Workout';
  exercises: Array<Exercise>;
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  sport: Scalars['String']['output'];
  tags: Array<Scalars['String']['output']>;
};
