#!/usr/bin/env node
// Emits dist/tokens.css and dist/tokens.dart from tokens.json.
// Dependency-free on purpose: four surfaces read these, none of them should
// have to install a token pipeline to do it.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const t = JSON.parse(readFileSync(join(here, 'tokens.json'), 'utf8'));

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const pascal = (s) => s[0].toUpperCase() + s.slice(1);

/* ---------------------------------------------------------------- CSS --- */

const colorVars = (theme, indent) =>
  Object.entries(t.color)
    .map(([name, v]) => `${indent}--botvy-${kebab(name)}: ${v[theme]};`)
    .join('\n');

const staticVars = [
  `  --botvy-font-family: ${t.font.family.map((f) => (f.includes(' ') ? `"${f}"` : f)).join(', ')};`,
  ...Object.entries(t.font.size).map(([k, v]) => `  --botvy-font-size-${kebab(k)}: ${v}px;`),
  ...Object.entries(t.font.weight).map(([k, v]) => `  --botvy-font-weight-${kebab(k)}: ${v};`),
  `  --botvy-line-height: ${t.font.lineHeight};`,
  ...Object.entries(t.radius).map(([k, v]) => `  --botvy-radius-${kebab(k)}: ${v}px;`),
].join('\n');

// Three-state theming: bare :root is light, the media query covers the
// "system" default without overriding an explicit light choice, and the
// [data-theme="dark"] block lets a toggle win in both directions.
const css = `/* GENERATED by packages/tokens/build.mjs from tokens.json — do not edit. */

:root {
  color-scheme: light dark;
${colorVars('light', '  ')}
${staticVars}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${colorVars('dark', '    ')}
  }
}

:root[data-theme="dark"] {
${colorVars('dark', '  ')}
}
`;

/* --------------------------------------------------------------- Dart --- */

const dartColor = (hex) => `Color(0xFF${hex.replace('#', '').toUpperCase()})`;

const dartColors = Object.entries(t.color)
  .flatMap(([name, v]) => [
    `  static const Color light${pascal(name)} = ${dartColor(v.light)};`,
    `  static const Color dark${pascal(name)} = ${dartColor(v.dark)};`,
  ])
  .join('\n');

const dartScale = [
  ...Object.entries(t.font.size).map(([k, v]) => `  static const double fontSize${pascal(k)} = ${v};`),
  ...Object.entries(t.font.weight).map(([k, v]) => `  static const int fontWeight${pascal(k)} = ${v};`),
  `  static const double lineHeight = ${t.font.lineHeight};`,
  ...Object.entries(t.radius).map(([k, v]) => `  static const double radius${pascal(k)} = ${v};`),
].join('\n');

// fontFamily is deliberately absent: the CSS stack is a fallback chain, which
// on Flutter is fontFamilyFallback. mobile feeds these to FlexColorScheme.
const dart = `// GENERATED by packages/tokens/build.mjs from tokens.json — do not edit.
import 'dart:ui' show Color;

class BotvyTokens {
  const BotvyTokens._();

${dartColors}

  static const List<String> fontFamilyFallback = <String>[
${t.font.family.map((f) => `    '${f}',`).join('\n')}
  ];

${dartScale}
}
`;

const dist = join(here, 'dist');
mkdirSync(dist, { recursive: true });
writeFileSync(join(dist, 'tokens.css'), css);
writeFileSync(join(dist, 'tokens.dart'), dart);
console.log(`tokens: wrote ${join('dist', 'tokens.css')} and ${join('dist', 'tokens.dart')}`);
